spring:
  datasource:
    url: jdbc:mysql://transaction-db.ctmcccmowvy6.eu-north-1.rds.amazonaws.com:3306/transaction-db
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    build-timestamp: '@maven.build.timestamp@'
    java:
      version: ${java.version}
      runtime: ${java.vm.name}

