#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/transaction-management
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://transaction-management.ctmcccmowvy6.eu-north-1.rds.amazonaws.com:3306/transaction-management?useSSL=false&serverTimezone=UTC
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.springframework.security: DEBUG

  jpa:
    hibernate:
      ddl-auto: create-drop  # Set to 'update' to keep existing data in the database and only update the schema if needed
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  sql:
    init:
      mode: always            # Ensures scripts are executed on startup
      data-locations: classpath:roles.sql  # Specify your SQL file location

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    build-timestamp: '@maven.build.timestamp@'
    java:
      version: ${java.version}
      runtime: ${java.vm.name}

