spring:
  datasource:
    url: jdbc:mysql://transaction-management.ctmcccmowvy6.eu-north-1.rds.amazonaws.com:3306/transaction-management?useSSL=false&serverTimezone=UTC
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    build-timestamp: '@maven.build.timestamp@'
    java:
      version: ${java.version}
      runtime: ${java.vm.name}