@startuml

actor User
entity "Users" as Users
entity "Account" as Account
entity "Transaction" as Transaction

User -> Users : POST /transaction-management-system/api/v1/users/login\n(Login User)
|||
Users --> User : 200 (JWT Token)
|||
|||
User -> Account : POST /transaction-management-system/api/v1/accounts/create\n(Create Account using JWT)
|||
Account --> User : 201 (Account Created)
|||
|||
|||
User -> Transaction : POST /transaction-management-system/api/v1/transactions\n(Create Transaction using JWT)
|||
Transaction --> User : 201 (Transaction Created)

@enduml
